name: lando-lemp
recipe: lemp
config:
  webroot: .
  config:
    vhosts: config/default.conf.tpl

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/lemp": ./../../